sonar.projectKey=brazil-data-cube

sonar.projectName=Brazil Data Cube

sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=brazil_data_cube/tests/**

sonar.tests=brazil_data_cube/tests

sonar.python.coverage.reportPaths=brazil_data_cube/tests/coverage.xml

sonar.host.url=http://localhost:9000

sonar.token=${env.SONAR_SECRET}

sonar.sourceEncoding=UTF-8

sonar.python.version=3.10.12