sonar.projectKey=brazil-data-cube

sonar.projectName=Brazil Data Cube

sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000

sonar.login=sqa_16614dd154dedbcdb5ada1a6a348f1bb6bb3ca1c

sonar.sourceEncoding=UTF-8